### ISSUE TITLE
--config_dir

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#109]
Options with the same name should indicate the same thing, but --config_dir expects different things between `amalgkit config` and `amalgkit metadata`. Could you rename that of `amalgkit config`?

**Comment by Hego-CCTB** [comment]
changed it to `--config_name` to make it match the help message that was already there: 
> Name of config folder to be created. Defaults to the original name within the package.

a42d5e612415b42b3be4c969cddc0e379fb7fcd3
