### ISSUE TITLE
TMM normalization

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#11]
Here is the script I used for TMM normalization in [this work](https://www.biorxiv.org/content/10.1101/409888v3).

[multispecies_normalization.ipynb.zip](https://github.com/kfuku52/amalgkit/files/4632980/multispecies_normalization.ipynb.zip)

Could you integrate it in the curate step or as a new subcommand?

**Comment by kfuku52** [comment]
@fsaul will need across-species TMM normalization in her project. When is this feature expected to be integrated?

**Comment by kfuku52** [comment]
@Hego-CCTB bump.

**Comment by Hego-CCTB** [comment]
I started looking into this. Expect a stable version by the end of next week!

**Comment by Hego-CCTB** [comment]
I've got your script running on my own plant data as well. Now it's just a matter of integrating it into curate. I might change some of the output folder structure of quant/merge to make it an easier transition into curate.

**Comment by Hego-CCTB** [comment]
I integrated cross species TMM normalisation into curate on my end (currently assumes very rigid folder structure and file names. Want to add options for that.). 

It also currently lacks a link to subsequent SVA correction. Currently (with TPM), if you have 4 different species you want to do SVA correction on, you'd have to run curate 4 times. But with TMM normalisation I have the info for all species in place already and could run SVA for all of them (seperately, in a queue). 

I'd add an option to stop after the TMM normalisation and one to automatically continue with the SVA for all species used in the TMM step.

**Comment by Hego-CCTB** [comment]
Also, if I assume a similar folder structure for TPM into SVA, there's nothing stopping me from doing the same for that branch of the algorithm as well (processing multiple species in a queue, that is). 

You think this is better or worse for the user?

**Comment by kfuku52** [comment]
It would be nice to have an option for sequential/parallel processing in both TPM and FPKM processings. And we clearly need a stop&resume for cross-species TMM and subsequent curations if parallel processing is desired... The stop&resume should be acceptable but wouldn't be a good design.

I'm wondering if it's possible to implement an optional subcommand like `amalgkit tmm` between quant and curate, so that we can use this command to apply a cross-species TMM normalization and get rid of the stop&resume in the curate step. To do so, we need to get "TMM-scaled counts" rather than "TMM-scaled FPKM/RPKM". I guess it's theoretically no problem to apply the TMM normalization factors to raw counts, but not entirely sure. Could you check if it's possible? If so, we should go with `amalgkit tmm`. If not, keep the stop&resume in the curate step.

You might want to check the original paper:
https://genomebiology.biomedcentral.com/articles/10.1186/gb-2010-11-3-r25

**Comment by kfuku52** [comment]
A quick test would be to compare if these two procedures return the same values:
1. raw count -> edgeR::calcNormFactors() -> manual tmm scaling -> edgeR::rpkm(foo, gene.length=bar, normalized.lib.sizes=FALSE)
2. raw count -> edgeR::calcNormFactors() -> edgeR::rpkm(foo, gene.length=bar, normalized.lib.sizes=TRUE)

**Comment by Hego-CCTB** [comment]
> A quick test would be to compare if these two procedures return the same values:
> 
> 1. raw count -> edgeR::calcNormFactors() -> manual tmm scaling -> edgeR::rpkm(foo, gene.length=bar, normalized.lib.sizes=FALSE)
> 2. raw count -> edgeR::calcNormFactors() -> edgeR::rpkm(foo, gene.length=bar, normalized.lib.sizes=TRUE)

Had exactly the same idea! Will report back on my findings

**Comment by Hego-CCTB** [comment]
Here's a scatterplot (FPKM vs FPKM) of the first 10000 genes in my test-dataset. Each dot represents a single gene, the x and y values being FPKM calculated in different order of operation. 
x-Axis (tmm_scaled_counts): 
Tmm scaling factor calculated based on raw counts -> scaling factor applied to the raw counts -> FPKM calculation based on scaled counts -> log2
y-Axis(tmm scaled fpkm):
Tmm scaling factor calculated based on raw counts ->FPKM calculation based on raw counts -> scaling factor applied to FPKM -> log2

This should be a straight line if both methods are identical.

![Scatterplot](https://user-images.githubusercontent.com/26280235/96002072-02554700-0e39-11eb-88f1-0c7c714a13d2.jpeg)

**Comment by Hego-CCTB** [comment]
Boxplot of the same data
![Boxplot_10000](https://user-images.githubusercontent.com/26280235/96002262-37fa3000-0e39-11eb-8a12-f30fcf0b7000.jpeg)

**Comment by kfuku52** [comment]
10k genes from one SRA or multiple?

**Comment by kfuku52** [comment]
Wouldn't it be straight diagonal if you plot each SRA separately after 52-sample TMM normalization? If so, there would be something to do with the library size. 
What we do currently with the default `lib.size` option is like: `rpkm(lib.size=total_count_after_tmm_scaling)`
So you can try `rpkm(lib.size=total_count_before_tmm_scaling)` and make the same plot again.

**Comment by Hego-CCTB** [comment]
Here are the first 4 Bioprojects (all 52 was too busy, couldn't see anything on the plot), still the same data as above. 

![image](https://user-images.githubusercontent.com/26280235/96008939-5ca5d600-0e40-11eb-8a0a-38bd0b805050.png)

**Comment by kfuku52** [comment]
Completely proportional! This means that TMM normalization is applicable to the raw counts. Could you try this?
>So you can try rpkm(lib.size=total_count_before_tmm_scaling) and make the same plot again.

**Comment by Hego-CCTB** [comment]
> Completely proportional! This means that TMM normalization is applicable to the raw counts. Could you try this?
> 
> > So you can try rpkm(lib.size=total_count_before_tmm_scaling) and make the same plot again.

I've been trying to, but the function does not let me change the lib.size parameter. I get this error when I change the parameter in any way (even setting it to NULL, which is part of the usage examples):
```

Error in rpkm.default(y = y$counts, gene.length = gene.length, lib.size = lib.size,  : 
  formal argument "lib.size" matched by multiple actual arguments
```

Currently trying to figure out, if it's on my side or if the function just doesn't permit changes to this parameter (it could be that a different function is called with the same parameter).

**Comment by Hego-CCTB** [comment]
Ok, looks like the function takes the lib.size directly out of the DGElist object created by calcNormFactors() for TMM normalization. I suspect this is why it refuses to take any input to the lib.size as lib.size is already "matched by another actual argument". 

Removing the lib.size data from the DGElist object leads the function to complain it can't find lib.size.
When I remove lib.size data from the DGElist object and supply the lib.size as an argument instead, I get both errors at the same time.

**Comment by kfuku52** [comment]
You can manually create a DGElist object with a manually given lib.size. I guess that a DGElist object is essentially a list with a simple structure (check by `str(obj)`) and a class name which you can give by `class(obj) = 'DGElist'`.

**Comment by Hego-CCTB** [comment]
> You can manually create a DGElist object with a manually given lib.size. I guess that a DGElist object is essentially a list with a simple structure (check by `str(obj)`) and a class name which you can give by `class(obj) = 'DGElist'`.

yup, I'm currently testing exactly that. The fpkm values I get now are much smaller, however. By "lib.size=total_count_before_tmm_scaling" I assume you mean the sum of all counts of a given SRR run, correct?

**Comment by kfuku52** [comment]
Yes, the sum of mapped reads. Could you share the script and input data? I'll take a look.

**Comment by Hego-CCTB** [comment]
[MSN_order_test.zip](https://github.com/kfuku52/amalgkit/files/5383989/MSN_order_test.zip)

That should be everything you need. Might have to adjust file paths slightly.

**Comment by kfuku52** [comment]
Why do some genes have non-integer counts?

Cla97C00G000550.1	45.1552	10.6436	19.697	55.1915	109.113	286.08	116.83	148.955	62.5674	147.764	19.6814	10.9908	15.1607	20.3287	11.1729	23.0078	31.6176	102.699	13.0827	18.8047	10.4348	31.6643	16.6954	44.0261	9.35973	6.50079	10.6587	25.9125	2.01264	75.5934	89.3125	18.6786	12.9305	5.7630300000000005	40.4928	168.958	18.2366	248.643	224.76	103.719	0.493075	14.0123	331.151	79.4392	6.63599	8.51185	151.76	86.8138	136.757	183.579	191.095

**Comment by kfuku52** [comment]
Ah, I just remembered that this is est_count from kallisto. No problem then.

**Comment by Hego-CCTB** [comment]
which file is that?

**Comment by kfuku52** [comment]
The root of the problem wasn't lib.size but normalization factors. The count values should have been divided by, not multiplied by, the normalization factor.
![image](https://user-images.githubusercontent.com/19270515/96112189-8e6f7900-0ee2-11eb-820d-1878da0990f0.png)

**Comment by Hego-CCTB** [comment]
ah, that would explain things! That's good news though, means order of operations are not relevant.

**Comment by Hego-CCTB** [comment]
Wait, wouldn't that make TMM normalized TPM possible?

**Comment by kfuku52** [comment]
Yes, operationally possible and it's OK to provide an option for TMM-TPM. But please note that not everybody thinks that TMM and TPM are compatible. See here for a relevant discussion.
https://groups.google.com/g/rsem-users/c/GRyJfEOK1BQ

**Comment by kfuku52** [comment]
How is the progress?

**Comment by Hego-CCTB** [comment]
`cstmm` is implemented and `curate` is now structured in a way that it takes in raw counts and effective length, so it can calculate FPKM or TPM by itself. So running `cstmm` first, then `curate` with the TMM-normalized counts is possible.

`cstmm` is running -as in not throwing errors- and the outputs _look_ fine, but I have no idea how to verify the results.
Here's one of the plots for the cross species normalized counts:

[Multisp.SVA.combined.pdf](https://github.com/kfuku52/amalgkit/files/6662498/Multisp.SVA.combined.pdf)


Note, that "corrected" and "uncorrected" are almost identical.

**Comment by kfuku52** [comment]
Is it TMM-TPM? By definition, TMM doesn't change TPM if applied prior to TPM calculation, so if one really wants to combine, TPM should be applied prior to TMM. Please look into the above URL.

**Comment by Hego-CCTB** [comment]
This should be FPKM. At least that's what I specified as input for the script. But I can't be 100% certain. I'll run it again.

**Comment by kfuku52** [comment]
I guess my point is:
- TPM -> TMM: This isn't theoretically valid but some people do so operationally. This is difficult under the current workflow of amalgkit, and so we don't have to support it.
- TMM-> TPM: This is meaningless as TMM normalization is completely canceled off by TPM transformation. Please return an error when `curate` is called with the TPM output and `cstmm` input. i.e., `curate` produces TPM output only when the input is `merge` files. This wouldn't be credibly detected if the users specify a custom input directory, but should've detectable if not (i.e., defaulted as `inferred`).

**Comment by Hego-CCTB** [comment]
yeah, that's true. I will include a general warning statement when `curate --norm = tpm`, just to at least partially cover custom input directories.
I haven't done a Wiki entry on `cstmm` yet, but there should be a warning there as well.

**Comment by kfuku52** [comment]
Sounds good!

**Comment by Hego-CCTB** [comment]
I have implemented a general warning when running `curate` with `tpm`, as well as an error (and program termination) when `cstmm` outputs are detected in the input file paths.

https://github.com/kfuku52/amalgkit/issues/49

**Comment by Hego-CCTB** [comment]
This issue seems done for now, as both cstmm and the warning messages have been implemented. 
Bugs and improvements can be done in new issues.

**Comment by kfuku52** [comment]
https://github.com/kfuku52/amalgkit/issues/11#issuecomment-1787489170

My correction above wasn't right. Division, rather than multiplication by a TMM normalization factor was a correct procedure indeed. I will revert the change in https://github.com/kfuku52/amalgkit/commit/22db4f582ff111232429b1ffa0157ee1d8edd51a.

Code for verification (works well after interactively running cstmm.r):
```
# EdgeR's TMM-CPM
head(edgeR::cpm(cnf_out2, normalized.lib.sizes=TRUE, log=FALSE, prior.count=0))

# Manually applied TMM transformation and subsequent CPM calculation. The values match with the above outputs.
df_nonzero_tmm = df_nonzero
for (col in colnames(df_nonzero_tmm)) {
    tmm_normalization_factor = cnf_out2[[2]][col,'norm.factors']
    df_nonzero_tmm[,col] = df_nonzero_tmm[,col] / tmm_normalization_factor # manually apply TMM normalization factors
}
tmp = cnf_out2
tmp[['counts']] = df_nonzero_tmm
head(edgeR::cpm(tmp, normalized.lib.sizes=FALSE, log=FALSE, prior.count=0))
```

**Comment by kfuku52** [comment]
With the correct "division" operation in a 114-species/3-tissue plant dataset:
Across-species among-sample variance of mean single-copy gene raw counts before and after TMM normalization: 351740.1 and 299518.9 
Across-species among-sample variance of all-gene mean raw counts before and after TMM normalization: 258562.6 and 262748.6 

[cstmm_mean_expression_boxplot.pdf](https://github.com/kfuku52/amalgkit/files/13249677/cstmm_mean_expression_boxplot.pdf)
[cstmm_normalization_factor_scatter.pdf](https://github.com/kfuku52/amalgkit/files/13249678/cstmm_normalization_factor_scatter.pdf)
