### ISSUE TITLE
removing unnecessary dependencies

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#120]
@Hego-CCTB Currently, AMALGKIT installs these packages by default: `'numpy','pandas','biopython','lxml','nltk','obonet'`. And I would like to minimize it before publication. I understand that `nltk` (`obonet` too?) were used in `amalgkit metadata --tissue_detect`, which did not work as well as we expected. We should keep the package dependencies if you are still using/developing this functionality, but they may be removed otherwise. Please let me know.

**Comment by Hego-CCTB** [comment]
Obonet and all related code can be safely removed. I'll take care of that.

**Comment by kfuku52** [comment]
I will take care of it.

**Comment by kfuku52** [comment]
done
