### ISSUE TITLE
sanity --updated_metadata_dir

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#121]
@Hego-CCTB I think we have already obsoleted updated metadata. Is this option still necessary?

**Comment by Hego-CCTB** [comment]
Yes, that option is not needed anymore. I also found some remnant code in sanity.py that didn't serve any purpose and removed it:

https://github.com/kfuku52/amalgkit/commit/faf9bb92514038bd70215003e557b815e82423dd

**Comment by kfuku52** [comment]
Thanks!
