### ISSUE TITLE
is_unpaird_file --> is_unpaired_file? 

### ISSUE THREAD

**Issue by docxology** [kfuku52/amalgkit#132]
At lines 464, 468, 470,474 in util.py
https://github.com/kfuku52/amalgkit/blob/9b5047e7dc91ad1cbeced9c52f5a93d9a2fbbe8a/amalgkit/util.py#L464
The variable is called "is_unpaird_file" -- maybe this is done for a reason, or complex to change.
However it might make sense to have this variable as "is_unpaired_file" for proper spelling (

**Comment by kfuku52** [comment]
Good catch! It's corrected now.
