### ISSUE TITLE
Obsoleting search_term_*.config

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#143]
I'm thinking to obsolete the following config files for `amalgkit metadata`, while the other optional config files are still vital (at least for now):
- search_term_exclusion.config
- search_term_keyword.config
- search_term_other.config
- search_term_species.config

...and introduce `--search_string` that directly accepts an Entrez search string for a more flexible search term specification. The usage would look like:
```
amalgkit metadata --search_string '("platform illumina"[Properties]) AND ("type rnaseq"[Filter]) AND ("Nepenthaceae"[Organism]) NOT ("DNA"[Source])'
```

@Hego-CCTB Does it sound OK? I believe this update improves customizability, but please let me know if there are any concerns.

**Comment by Hego-CCTB** [comment]
Yes, this would be a huge improvement!

**Comment by kfuku52** [comment]
done!

**Comment by kfuku52** [comment]
Wiki has been updated:
https://github.com/kfuku52/amalgkit/wiki/amalgkit-metadata
