### ISSUE TITLE
Code for rRNA rate 

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#145]
If you must add code specific to another project, ensure it doesn't alter the default behavior. Preserving the default behavior would have prevented the unnecessary debugging I had to undertake this time.

https://github.com/kfuku52/amalgkit/blob/5f1083e12fadc950280959d72348e73446bdaede/amalgkit/curate.r#L542

https://github.com/kfuku52/amalgkit/blob/5f1083e12fadc950280959d72348e73446bdaede/amalgkit/curate.r#L828

These codes introduce unnecessary brackets to `curate` output plots like this:
<img width="352" alt="image" src="https://github.com/kfuku52/amalgkit/assets/19270515/e1ee5d5d-b449-42a5-a970-be9ea029a8a4">

**Comment by kfuku52** [comment]
If you have read this issue, please close.

**Comment by Hego-CCTB** [comment]
Acknowledged! I'll be more careful in the future!
