### ISSUE TITLE
Output uncorrected tables without going through all of curate

### ISSUE THREAD

**Issue by Hego-CCTB** [kfuku52/amalgkit#147]
We recently encountered a case, where samples were (intentionally) extremely similar to each other, despite being tagged as different tissues. This led to amalgkit removing a couple of samples. Additionaly for that dataset, we didn't need the amalgkit corrected output at all. So it would be nice to have an option to just output all data before the SVA correction and then stop, saving some time in cases where SVA correction is not desired.

**Comment by Hego-CCTB** [comment]
Done here: 
9a63d9dfd7cb9e30db31a8d341adceea6bab73c7

`--skip_curation yes` stops `curate` after the transformation of the  count table and the curate_group.mean version of that table and before any kind of batch-effect removal/outlier removal/mapping-rate cut-off.
`--skip_curation no` behaves normally (default. https://github.com/kfuku52/amalgkit/commit/22e34c6d2779138bb7729d37e300a89fab9b54a9).

**Comment by kfuku52** [comment]
Thank you. Could you bump the version?

**Comment by Hego-CCTB** [comment]
done
