### ISSUE TITLE
Metadata example command

### ISSUE THREAD

**Issue by docxology** [kfuku52/amalgkit#149]
At: 
https://github.com/kfuku52/amalgkit/wiki/Amalgkit-metadata

I see the following example usage of "amalgkit metadata": 

`amalgkit metadata  --out_dir "./" --entrez_email "example@email.com" --search_string 'metadata --redo no --search_string '("platform illumina"[Properties]) AND ("type rnaseq"[Filter]) AND ("Nepenthaceae"[Organism]) NOT ("DNA"[Source])'
`
This is a bit confusing because --search_string is given twice, once with 'metadata (?) and once with a longer string that seems more relevant for that required argument.  

I am getting successful operation with the use of: 
amalgkit metadata --search_string '("platform illumina"[Properties]) AND ("type rnaseq"[Filter]) AND ("Apis mellifera"[Organism]) NOT ("DNA"[Source])'

**Comment by kfuku52** [comment]
Thank you for bringing this to our attention! This has now been corrected.

**Comment by docxology** [comment]
Thank you Kenji. 
I am making sure that my pipeline continues to work with the recent updates to amalgkit & will let you know if I have any other questions.

**Comment by kfuku52** [comment]
Thank you for your continued support!
