### ISSUE TITLE
curate_group -> sample_group

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#151]
@Hego-CCTB I think `sample_group` is more appropriate and clear than `curate_group`. Is it OK to make this change in the future?

**Comment by Hego-CCTB** [comment]
Absolutely. In the paper I called it sample group as well, since it's clearer for the reader.

**Comment by kfuku52** [comment]
OK, this should be done before the paper submission.

**Comment by kfuku52** [comment]
done.
