### ISSUE TITLE
raise Exception if returncode is not zero.

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#19]
It would be nice for debugging if amalgkit throws an error when external tools do not exit correctly. Here is an example code. Could you insert similar assertions or `raise Exception()` in relevant places?
```
    run_iqtree = subprocess.run([g['iqtree_exe'], '-s', g['alignment_file'], '-te', g['rooted_tree_file'],
                                 '-m', g['iqtree_model'], '--seqtype', 'CODON'+str(g['genetic_code']),
                                 '--threads-max', str(g['threads']), '-T', 'AUTO', '--ancestral', '--rate', '--redo'],
                                stdout=sys.stdout, stderr=sys.stderr)
    assert (run_iqtree.returncode==0), "IQ-TREE did not finish safely: {}".format(run_iqtree.stdout.decode('utf8'))
```

**Comment by Hego-CCTB** [comment]
Makes sense, I'll look into it.

**Comment by Hego-CCTB** [comment]
For debugging, I'll use assert() for the time being. 

For error handling in a final release, it might be preferable to use try/except constructs, according to [opinions on stackoverflow.](https://stackoverflow.com/questions/40182944/whats-the-difference-between-raise-try-and-assert).

**Comment by Hego-CCTB** [comment]
forgot to push this update. Rectified now.
