### ISSUE TITLE
cstmm R package dependency

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#22]
Currently, `cstmm` depends on these:
```
library(limma)
library(tidyr)
library(dplyr)
```
Do they all really necessary? In principle, dep packages should be minimal, and we should use base R functions instead of packages if the same process can be accomplished in a not-so-complicated way. we do need `edgeR` but how do we use `limma`-specific functions here? `tidyr` and `dplyr` speed up our exploratory data analysis, but for programs like `amalgkit`, they are more like so-called "technical debt" because they are not essential but increase the installation complexity.

**Comment by Hego-CCTB** [comment]
These were probably remnants from testing. None of these packages were actually in use. I cleaned them up in 1b3b78bb1424a2723b0ad297b017324edfc1e319
