### ISSUE TITLE
species-wise merge

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#23]
`merge` should be done for each species but not implemented so currently.

**Comment by kfuku52** [comment]
This will make it easier to handle the data in the curate step as it should be done species-wise. It would be nice to store the merge outputs in species-wise directories like `work_dir/merge/GENUS_SPECIES/`. Could you work on this?

**Comment by kfuku52** [comment]
I think we had a conversation years ago on how amalgkit outputs should be structured. Do you still have the note I took? You can follow that.

**Comment by Hego-CCTB** [comment]
Amalgkit update 0.5.1.1:
- `amalgkit merge` now organises output species-wise when `metadata` guided

<img width="310" alt="Screenshot 2021-06-16 at 16 11 53" src="https://user-images.githubusercontent.com/26280235/122235162-c2f66300-cebd-11eb-86ce-221465116b39.png">

https://github.com/kfuku52/amalgkit/commit/ff964bc39848f6c981242108e884764c4b54a3c1
