### ISSUE TITLE
curate infiles

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#24]
@Hego-CCTB Some of the curate infile PATHs are handled in a weird way. It's jointed with `--work_dir` like below, so it assumes a truncated relative PATH to be provided. This is not something users can easily expect. Could you change them so that users can provide the full PATH or the complete, not truncated, relative PATH?
```
meta_out = os.path.join(args.work_dir, args.metadata)
```
(By the way, --metafile will be renamed to --metadata in `curate` in my next push to make it consistent with the other amalgkit subcommand.)

**Comment by Hego-CCTB** [comment]
curate should now require full paths.
