### ISSUE TITLE
cstmm inputs

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#29]
It looks like `cstmm` is decoupled from `merge`, because `merge` doesn't produce a directory which can be specified as `--count` in `cstmm`. Do you manually edit file names and directory structures?

**Comment by kfuku52** [comment]
Patched by the above commit. `merge` now produces species-wise outputs. All species will appear in a single output directory, but they should be separately stored in species-wise directories in the future.

**Comment by Hego-CCTB** [comment]
Let's continue this here:
https://github.com/kfuku52/amalgkit/issues/29

**Comment by kfuku52** [comment]
The link would be wrong.

**Comment by Hego-CCTB** [comment]
fixed
