### ISSUE TITLE
Implement quant

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#3]
The `metadata` command should be followed by the `quant` command which isn't implemented yet. The command should look like:
`amalgkit quant --id SRR6337924 --fastp yes --threads 8 --ref Anolis_carolinensis_genes.fasta`

`quant` should deal with the following steps for one SRA entry at a time:
* Downloading a SRA file by parallel-fastq-dump or pfastq-dump
* Data cleaning by fastp
* Quantification by kallisto (other tools can be supported in future)

We have a prototype [bash file](https://github.com/kfuku52/amalgkit/blob/master/util/kallisto_20180207.sh) for this command.

**Comment by kfuku52** [comment]
I completely forgot that `fasterq-dump` made available already.
https://github.com/ncbi/sra-tools

We can use it instead of a wrapper (parallel-fastq-dump/pfastq-dump).

**Comment by kfuku52** [comment]
Great. One drawback fasterq-dump currently has would be no support for subsampled output. For this reason, I still have to use parallel-fastq-dump for amalgkit getfastq (will be pushed soon) for a while.

**Comment by Hego-CCTB** [comment]
Good to know!

I timed the download of a paired-end Illumina run on fasterq-dump, pfastq-dump and the normal fast-dump. The file is 8.52 GB large, x2 because paired end.
The normal fast-dump on a single core took 4 min 6 sec.
`fastq-dump --split-3 SRR8819967`
fasterq-dump took 46 sec.
`fasterq-dump SRR8819967 -3 -e 4`
pfastq-dump took 1 min 14 sec
`parallel-fastq-dump -t 4 --split-3 --outdir ./  -s SRR8819967`

Not super representative, of course, but fasterq is ~30 seconds faster for this file than pfastq.

**Comment by kfuku52** [comment]
40% speedup would be very nice. 

I just updated the master. amalgkit getfastq is now available. It still depends on parallel-fastq-dump because I need subsampling (`--max_bp`) immediately. If you wanna test it, please reinstall your parallel-fastq-dump, which was updated yesterday to properly support a read range specification.

You can either (1) implement a new getfastq-ish subcommand that depends only on fasterq-dump (and merge them in future) or (2) modify getfastq.py to be able to take advantage of fasterq-dump when subsampling is non-necessary.

**Comment by Hego-CCTB** [comment]
hmm. I'm getting this error:

> File "/anaconda3/bin/amalgkit", line 99, in <module>
>     args.handler(args)
>   File "/anaconda3/bin/amalgkit", line 29, in command_getfastq
>     getfastq_main(args)
>   File "/anaconda3/lib/python3.6/site-packages/amalgkit/getfastq.py", line 156, in getfastq_main
>     spot_length = int(metadata.df.loc[i,'spot_length'])
> ValueError: invalid literal for int() with base 10: ''
> 

looks like "spot_length" is empty (the .tsv also has no value for spot_length). I've tried several accessions (all randomly pulled from SRA), with the same error message. My pfastq-dump seems to be on the correct version:

`s229181$ parallel-fastq-dump -V`

> parallel-fastq-dump : 0.6.4
> 
> fastq-dump : 2.9.1 ( 2.9.1-1 )

**Comment by kfuku52** [comment]
Could you share the tsv?

**Comment by Hego-CCTB** [comment]
One's an arabidopsis accession, the other one's mouse. 

[Archive.zip](https://github.com/kfuku52/amalgkit/files/3089926/Archive.zip)

**Comment by Hego-CCTB** [comment]
both lack any data for:

nominal_length | nominal_sdev | spot_length | read_index | read_class | read_type | base_coord

**Comment by kfuku52** [comment]
Updated. Should work fine now.

**Comment by Hego-CCTB** [comment]
yes, works for me now!

**Comment by Hego-CCTB** [comment]
Still getting used to python and IntelliJ, but I came up with a tiny prototype script that passes arguments from `amalgkit quant` to `kallisto`. It's fairly unimpressive right now, since the user could just use kallisto directly instead. So I'm thinking of features to be added. I think, it would be nice to automatically quantify all fastq files (wether downloaded by `getfastq` or by the user) in a given directory. The biggest issue here are probably reference genomes and mixes of single-end/paired-end reads.

**Comment by kfuku52** [comment]
Great! It's always good to start from the simplest framework; It's gonna be rapidly complicated and spiral out of control soon : ) One of the important points of the `quant` step would be to make the output file path and format compatible with the subsequent `curate` step. So I expect many tweakings after you start working on it.

For now, manual specification would be fine, like:
`amalgkit quant --id SRR00000 --ref Homo_sapiens.gene_models.fasta --layout single`

But the layout specification could be relatively easily automated by looking at whether there are ${id}_1...fastq.gz and ${id}_2...fastq.gz or only ${id}...fastq.gz.

**Comment by Hego-CCTB** [comment]
It's pretty close to that already! Still needs error handling, though. 

Also in the specific case of single-end files, kallisto needs fragment length and fragment standard deviation. Can this be calculated from the .fastq files somehow, or fetched from the metadata?

**Comment by kfuku52** [comment]
"nominal_length" in metadata is what's expected as the fragment length but is not always available and sometimes totally incorrect (e.g., just 0, it's impossible). It's usually not possible to estimate from single-end reads. If it's not in the metadata, we have to use a placeholder value. The situation is almost same for the SD.

In my previous work, it was decided like this. If the values were smaller than 200 nt, it was rounded up to 200 nt to correct unnaturally small values, and the SD was set to 10% of the nominal length. I admit that this is somewhat arbitrary though.
```
nominal_length=`cat ${sra_table} | awk -F "\t" "NR==${row}" | awk -F "\t" '{print $35}' | sed -e "s/\..*//"` ; echo nominal_length: ${nominal_length}
if [ -z "${nominal_length}" ] || [ ${nominal_length} -lt 200 ]; then
	nominal_length=200
fi
echo adjusted nominal_length: ${nominal_length}
nominal_sd=$[${nominal_length}/10]; echo nominal_sd: ${nominal_sd}
```

**Comment by Hego-CCTB** [comment]
Ok, I pushed a working version of `amalgkit quant` to the `devel` branch. Should be able to handle both single and paired end data. In the case of single end reads, it checks whether it can find a SRA ID and pulls the metadata for that ID (I just used the relevant getfastq functions for that). If it doesn't recognise an ID, doesn't find an entry, or the nominal length is empty/lower than 200, a length of 200 is assumed. However, I'm not entirely sure if I access the metadata.df correctly. 

Also, for the time being, `amalgkit quant` assumes that all input files are inside the working directory.

No idea why the username on the push is not correct, pretty sure it's related to IntelliJ, but I can't find the settings to change that. <.<

**Comment by kfuku52** [comment]
Great! Could you add a simple example of usage in README.md? I quickly went through the code and found that the getfastq's sub-parser was overwritten by quant's sub-parser; Please change the object name (parser_getfastq -> parser_quant).

At the beginning of the main function, it would be better to test whether kallisto is installed like this:
```
    test_pfd = subprocess.run(['parallel-fastq-dump', '-h'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    assert (test_pfd.returncode==0), "parallel-fastq-dump is not installed."
```

os.path.join() parses paths better than string concatenation with "+"; You would no longer have to worry about whether a directory path ends with "/" or not.

**Comment by Hego-CCTB** [comment]
Wow, how did I miss that parser? 

Most of the changes should be up, os.path.join() is next. I tested installation with a `try/except` block, since `assert` can apparently be circumvented by the user.

**Comment by kfuku52** [comment]
Thanks! I will review it later. Now you can start working on `amalgkit curate` with a test dataset which is small but comes from multiple BioProjects. You would need to run an R script like this from python:

```
Rscript transcriptome_data_preparation.r \
quant_outfile.tsv \
metadata.tsv \
PATH_TO_OUTPUT_DIR \
'pearson' \ # distance calculation method
0.2 \ # mapping rate cutoff
0 \ # This is an almost obsoleted option. Leave it zero.
1 \ # Whether or not to print intermediate files
'brain|heart|kidney|liver|ovary|testis' # tissues to be included. Can be obsoleted if it's defined in an earlier step.
```
The arguments are all positional. Please include `transcriptome_data_preparation.r` in the amalgkit/amalgkit directory (with modification if needed).

#### Mapping rate cutoff
In this example, a sample is removed if no more than 20% of RNA-seq reads are mapped to the reference. We need to add a new column in the metadata tsv for the mapping rate values which should be collected from the kallisto stdout or log files.

**Comment by kfuku52** [comment]
If the IDEA problem persists, you can fork the repo to your account. I guess the problem is not gonna happen as long as you work in your own repo.

**Comment by kfuku52** [comment]
@Hego-CCTB It seems like `quant` doesn't support a batch job processing. We need it to scale the amalgkit analysis to thousands of RNA-seq data. Can I work on it? I'm thinking to introduce an option `--batch INT` to make individual jobs can download sra and run kallisto separately. Here, INT specifies the row number in the metadata table. Please let me know if there is anything that hampers such parallel handling.

**Comment by kfuku52** [comment]
Oh, wait. Doesn't `quant` take metadata table as input?

**Comment by Hego-CCTB** [comment]
> Oh, wait. Doesn't `quant` take metadata table as input?

Not yet, because it wasn't needed up until now. And since I'm processing tpm calculation and mapping rate in curate on the `dev` branch, I didn't think about including metadata tables.

**Comment by Hego-CCTB** [comment]
> @Hego-CCTB It seems like `quant` doesn't support a batch job processing. We need it to scale the amalgkit analysis to thousands of RNA-seq data. Can I work on it? I'm thinking to introduce an option `--batch INT` to make individual jobs can download sra and run kallisto separately. Here, INT specifies the row number in the metadata table. Please let me know if there is anything that hampers such parallel handling.

Sure, go ahead!

**Comment by kfuku52** [comment]
OK, I will start soon. Please push your dev to master if there are any changes in metadata/getfastq/quant and no apparent bugs.

**Comment by kfuku52** [comment]
kallisto index is meant for the reference. We don't need to generate one index per RNA-seq fastq, but one per reference. I will fix it.
