### ISSUE TITLE
deprecated --threads

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#35]
Why did you remove --threads from quant in 970b0ca?

**Comment by Hego-CCTB** [comment]
I have no idea. The only reason I can think of, is that I saw that `kallisto index` doesn't have a --threads argument and assumed this would be the case for all kallisto subfunctions.

In any case, `--threads` is back in now.
0de41f1

**Comment by kfuku52** [comment]
In checking the commit, I found this.
`print("Job failed to submit".format(submit_command))`
`{}` is needed for the place you want to insert a string. Also, I assume `submit_command` is a list, and if so, this should be joined before passing to `format()`.

**Comment by Hego-CCTB** [comment]
While fixing this, I came across a couple of other issues as well. This should work now, but I think `quant` needs more work. Will continue this in another thread.

b52cd0d78bcf317123778e46dcae0ebc2bda7505
