### ISSUE TITLE
curate output files

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#36]
`curate` generates all output files under --work_dir. They should be organized into sub-directories under `amalgkit_out/curate/`.

**Comment by Hego-CCTB** [comment]
Curate output is now in line with the rest of amalgkit:

    -curate
       --tables
         ---Genus_species.*.pdf
       --plots
         ---Genus_species.*.tsv
      --rdata
         ---Genus_species.sva.round.RData

we could also additionally create a folder `Genus_species` between the `tables/plots/rdata` and `curate`.

**Comment by kfuku52** [comment]
Thank you. This directory structure would be satisfactory for now. We can use this structure for a while and update it if it's not convenient enough.
