### ISSUE TITLE
cstmm output files

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#37]
I noted that `cstmm` generates `normalization_factor_histogram.pdf` and `normalization_factor.tsv` under --work_dir. These files should be stored under a new subdirectory.

**Comment by Hego-CCTB** [comment]
i brought the cstmm output folder structure in line with the  rest of amalgkit:

     -cstmm/
      --cross_species_tmm_normalized_counts/
         ---Genus_species_cstmm_counts.tsv
      --normalization_factor_histogram.pdf
      --normalization_factor.tsv

9847d53
