### ISSUE TITLE
change --work_dir

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#38]
--work_dir may not be the best name to represent the functionality of this option. People would expect something like --outdir, because --work_dir sounds like it's a place to generate temporary files.

**Comment by Hego-CCTB** [comment]
Changed `--work_dir ` to  `-w, --out_dir` in all places (-o was already occupied for the  --overwrite flag. We can switch them around tho, since -o is probably gonna be used more).

b5418de

**Comment by kfuku52** [comment]
Thanks. We can re-organize the shorter flag later.
