### ISSUE TITLE
quant overhaul

### ISSUE THREAD

**Issue by Hego-CCTB** [kfuku52/amalgkit#40]
While fixing some minor bugs in `quant`, it became clear that `quant` needs some love.

- obsolete `--build_index`
- make metadata a required input
- read library type(single/paired end) and fragment length directly from the local metadata, instead of querying SRA again.
- the way kallisto is called currently makes it harder to implement alternative quantification programs (such as salmon)
- theoretically, the mapping rate can be directly taken from the kallisto output

@kfuku52 what's your opinion on this?

**Comment by kfuku52** [comment]
Agreed except
>the way kallisto is called currently makes it harder to implement alternative quantification programs (such as salmon)

I've never used salmon but wouldn't it be easy to introduce a new option like `amalgkit quant --mapper "salmon"` and change the behavior accordingly? I expect some reformatting is needed afterward but that wouldn't be fundamentally difficult.

**Comment by Hego-CCTB** [comment]
What I was thinking of, was to put all kallisto related code into a function like run_kallisto() and make a separate function for alternatives, since input/output formats may vary.

**Comment by Hego-CCTB** [comment]
- `--build_index` is now obsolete
- `--ref` is now replaced by `--index`
- metadata is now a required input
- library type and fragment length are now read out from the metadata directly
- removed unused dependencies
- restructured code to modularize kallisto call

https://github.com/kfuku52/amalgkit/commit/2052d6f5475f10ea0f69adcecd408db4d99b9f25
