### ISSUE TITLE
BUSCO for cstmm

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#42]
Typically, more single-copy genes can be detected with BUSCO compared with Orthofinder. It doesn't hold the highest priority, but the BUSCO input for cstmm could be a future improvement.

**Comment by Hego-CCTB** [comment]
yes, I had a similar thought, as I'm currently preparing my data for BUSCO single-copy identification. This will be needed  for the upcoming `amalgkit csca` as well.

**Comment by kfuku52** [comment]
amalgkit needs reference transcriptomes anyway, so BUSCO runs could be included as a part of an amalgkit subcommand. It's difficult to do so with OrthoFinder because its computational time should increase exponentially with the number of species. However, BUSCO scales only linearly with species, so it's doable.

**Comment by kfuku52** [comment]
@Hego-CCTB I will take care of it if you don't have time.

**Comment by kfuku52** [comment]
done
