### ISSUE TITLE
consistent colors between curate and csca

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#43]
Tissue colors do not match between curate and csca pdf files.

**Comment by Hego-CCTB** [comment]
It looks like they aren't consistent within csca either. `multisp_tsne.pdf` shares the coloring with `curate`, but the rest of the output doesn't. I'll try to make tissue coloring dependent on order of input for both.

**Comment by kfuku52** [comment]
This would be an easy fix. You can use sort() in the function that annotates tissue/bioproject/species colors.

**Comment by Hego-CCTB** [comment]
maybe add coloration info into metadata table. TODO

**Comment by kfuku52** [comment]
@Hego-CCTB I will take care of it if you don't have time.

**Comment by kfuku52** [comment]
This should have been solved as long as the number of the curate_group categories does not differ between curate and csca.
