### ISSUE TITLE
curate wiki

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#64]
@Hego-CCTB Could you include one more heatmap which shows the data before SVA & after outlier removal?
https://github.com/kfuku52/amalgkit/wiki/Amalgkit-curate

**Comment by Hego-CCTB** [comment]
Where would you want to include this? As an example in the output section?

**Comment by kfuku52** [comment]
The new heatmap should sit between the heatmaps 1 and 2, like Fig. 1 of this paper. https://www.nature.com/articles/s41467-020-18090-8

**Comment by Hego-CCTB** [comment]
Something akin to this? I've updated the workflow as well, to reflect the current state of amalgkit.

<img width="1633" alt="Screenshot 2021-07-08 at 16 32 25" src="https://user-images.githubusercontent.com/26280235/124940368-36494b80-e00a-11eb-8f7a-44530b7d6c9b.png">

**Comment by kfuku52** [comment]
Great! Also, the numbers (2 and 3) in the workflow should be on arrows, not boxes, because it would be ambiguous whether the step (box) is applied already or not.

**Comment by Hego-CCTB** [comment]
Done!
