### ISSUE TITLE
Suggested annotation by Zooma

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#67]
There is an API so programmatic access should be straightforward.
https://www.ebi.ac.uk/spot/zooma/docs/api

**Comment by Hego-CCTB** [comment]
that'll do!

My approach would be to have Zooma in addition to the config (as an option), but prefer config entries over Zooma in cases of overlap.

**Comment by kfuku52** [comment]
That sounds good. Manual curation/confirmation is unavoidable anyway, but the suggested curation would greatly help.

**Comment by kfuku52** [comment]
Should we discontinue this?

**Comment by kfuku52** [comment]
Should we discontinue this, or do you want to continue it?

**Comment by Hego-CCTB** [comment]
I think we should discontinue. This would be at the bottom of my priorities regarding amalgkit and even if implemented, Zooma can still be very wrong and still needs human supervision after annotation.

**Comment by kfuku52** [comment]
OK!
