### ISSUE TITLE
confusion matrix

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#68]
We might want to incorporate some approaches this paper employed.
https://academic.oup.com/nargab/article/3/3/lqab077/6363752

Among others, the confusion matrix in Fig. 2B would be informative. @Hego-CCTB would you be able to include it in the `curate` plots?

**Comment by kfuku52** [comment]
Perhaps 2A too.

**Comment by Hego-CCTB** [comment]
Sure!

I'll probably come back with questions regarding this.

**Comment by Hego-CCTB** [comment]
Bump!

**Comment by kfuku52** [comment]
Closing this issue for now because its priority isn't high.
