### ISSUE TITLE
amalgkit integrate is too slow

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#69]
`integrate` requires several minutes per fq.gz. Perhaps `seqkit stat` doesn't have to read all fastq reads. The First 100 reads or so should be enough to obtain the read length. Total size is read length x read number. However, getting read number wouldn't be straightforward: `zcat C1D_1.fq.gz | grep "^@" | wc -l` took a minute or so. An alternative approach would be necessary for substantial speed up.

**Comment by Hego-CCTB** [comment]
Okay, I implemented the changes to the seqkit input and here is a quick comparison between the old implementation (full seqkit) and the new one (head seqkit). The top 2 entries are the old implementation for single and paired samples and the bottom 2 are the same samples calculated with the new implementation. 

scientific_name | curate_group | run | read1_path | read2_path | is_sampled | is_qualified | exclusion | lib_layout | spot_length | total_spots | total_bases | size | private_file | runtime
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
full seqkit, single | flower | trimmed-PAuF | /Users/s229181/Desktop/seq_data/Data/SD/getfastq/trimmed-PAuF_1.fq.gz | no path | yes | yes | no | single | 148.4 | 31190694 | 4627300802 | 2319701462 | yes | 46s
full seqkit, paired | flower | trimmed-PAuF | /Users/s229181/Desktop/seq_data/Data/SD/getfastq/trimmed-PAuF_2.fq.gz | /Users/s229181/Desktop/seq_data/Data/SD/getfastq/trimmed-PAuF_1.fq.gz | yes | yes | no | paired | 148.3 | 31190694 | 9253736528 | 2445176519 | yes | 46s
head seqkit, single | flower | trimmed-PAuF | /Users/s229181/Desktop/seq_data/Data/SD/getfastq/trimmed-PAuF_1.fq.gz | no path | yes | yes | no | single | 148.4 | 31190694 | 4616222712 | 2319701462 | yes | 27s
head seqkit, paired | flower | trimmed-PAuF | /Users/s229181/Desktop/projects/sanity_test_wd/trimmed-PAuF_2.fq.gz | /Users/s229181/Desktop/seq_data/Data/SD/getfastq/trimmed-PAuF_1.fq.gz | yes | yes | no | paired | 148.4 | 31190694 | 9232445424 | 2445176519 | yes | 27s

As expected, the total bases are not completely accurate. For the paired samples, they differ by about 21 million bases. This sounds a lot, but it's just a 0.2% difference. The loss of accuracy may be well worth the gain in speed. This particular sample is already trimmed and fairly small, so the old runs didn't take too long. I'll test this with larger files, where I know that the old version took 20+ minutes per sample.

**Comment by Hego-CCTB** [comment]
As a side note, this process could be made even faster by utilizing the gnu parallel for zcat. However, we run into the problem with macOS again, where parallel needs to be installed via brew first. 

I will test the potential gain in speed and if it's significant, I'll implement a branch which uses `parallel` if it's installed and the normal zcat if ont.

**Comment by Hego-CCTB** [comment]
Reminder for myself to reintroduce the slow method.

**Comment by Hego-CCTB** [comment]
`--accurate_size yes|no` is now a parameter to run the slow, but more accurate seqkit. 

https://github.com/kfuku52/amalgkit/commit/acff42d3c652bee8efc95ccaf8993afa303588d9
