### ISSUE TITLE
Index file detection in amalgkit sanity

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#72]
```
Looking for Index file ./Index/Arabidopsis_thaliana* for species:  Arabidopsis thaliana
Found  ['./Index/Arabidopsis_thaliana_Athaliana-167-cds-primaryTranscriptOnly.fa'] !
```
I'm not sure what `sanity` does here. It says that the index is found and shows the PATH to reference fasta I put in amalgkit_out/Index. Should fasta be in another directory? 

Also, help messages are not user-friendly. In many cases, "Index" does not make sense if you don't mention the "reference fasta".

Minor point: Does the default "Index" dir has to be the title case even though all other subdirs do not have a capitalized first letter?

**Comment by Hego-CCTB** [comment]
Bumb for myself!

**Comment by Hego-CCTB** [comment]
I have reintroduced index building to `quant`.
The way this works is the following:
`--fasta_dir PATH` indicates folder containing fasta files with species names, required for building index
`--build_index yes|no` enables functionality

goes through `quant` as normal. If `--build_index yes`, `quant` will look for the currently processed species according to the metadata file in the index directory first. If there is no available index for that species,`quant` fill try to find a matching fasta file in the `--fasta_dir` and start building the index. `quant` will then immediately go on quantifying samples as normal.

https://github.com/kfuku52/amalgkit/commit/6f7971b83bb6be07b2c7de9922fcf521c13e94ca
and
https://github.com/kfuku52/amalgkit/commit/23c824c750dd4bcc540fc2a68144bf7faa62449d (safer fasta file detection)
