### ISSUE TITLE
Invalid values in is_sampled and is_qualified

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#74]
`integrate` prefills 'yes' in is_sampled and is_qualified, but that is not a valid value, and therefore `getfastq` automatically excludes the sample from analysis. The valid values are either 'Yes' or 'No'. @Hego-CCTB Could you fix it? You might want to use `strtobool` to relax the allowed variation.

**Comment by Hego-CCTB** [comment]
I rewrote load_metadata() to use strtobool. Changed `integrate` too, just in case. 

https://github.com/kfuku52/amalgkit/commit/e1428b8fd1ed1109528d6b07b90f9ae03d60feaf
