### ISSUE TITLE
redundant codes in quant

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#78]
`load_metadata(args)` takes care of --batch (and probably should do so too to --id), so I'm not sure if these three branch conditions are really necessary. @Hego-CCTB What do you think?

https://github.com/kfuku52/amalgkit/blob/9698f58f4def61cdff9cb1f3e9388132ed9594e6/amalgkit/quant.py#L150-L179

**Comment by Hego-CCTB** [comment]
Sure!

**Comment by Hego-CCTB** [comment]
Did some testing and, yes, this codeblock can be safely removed!

My PyCharm is currently having issues with Git, but I'll push an update as soon as I figure that one out.

**Comment by Hego-CCTB** [comment]
Never came back to close this. That code has been removed.
