### ISSUE TITLE
restarting with preexisting directory

### ISSUE THREAD

**Issue by kfuku52** [kfuku52/amalgkit#8]
When I use getfastq, create_run_dir() always tries to make a new directory. Could you implement an option to use a specified preexisting directory so that amalgkit can detect some files like .sra and skip time-consuming steps?

**Comment by Hego-CCTB** [comment]
I changed the directory creation so that it appends the run-ID instead of an increasing number. That way both bulk download and reusing .sra files for the same run is possible.

**Comment by Hego-CCTB** [comment]
I will still make this optional and let the user define a specific directory.

**Comment by kfuku52** [comment]
`metadata` seems to create a new outdir each time. Could you make it optional consistently? (perhaps `curate` too?)

**Comment by Hego-CCTB** [comment]
on it! Shouldn't take too long.

**Comment by Hego-CCTB** [comment]
everything should be optional now. Also fixed some other minor bugs.
