### ISSUE TITLE
.tsv's have columns shifted by one in amalgkit output

### ISSUE THREAD

**Issue by C20H25N30** [kfuku52/amalgkit#86]
As per the https://github.com/kfuku52/amalgkit/issues/85 table copied in from Species.tau.tsv -- I find that in /curate/tables/, some TSV files have a deleted first column name (should be e.g. "locus_ID" or "gene_ID"), and all other columns are shifted over. This causes improper behavior for downstream pipelines and my fix has only been to manually add in a column name for gene_ID and shift other columns to the right. 

This error in the TSV is seen in the following files in Tables/
Species.tau
Species.tc
Species.uncorrected.curate_group.mean
Species.uncorrected.tc
Species.curate_group.mean

The .sva and .sra TSV column names are fine.

**Comment by Hego-CCTB** [comment]
Ah, this is probably because they are matrices with the genename as a row identfifier, rather than being an entry in a column. So when they are saved by R, they don't get a column name and everything shifts over.

I'll take care of this!

**Comment by C20H25N30** [comment]
Thank you @Hego-CCTB !

**Comment by Hego-CCTB** [comment]
Added a "GeneID" column name to the .tsv outputs in amalgkit ver. 0.5.1 
https://github.com/kfuku52/amalgkit/commit/0bf4fc3083336883b3aab8aed87b1f1f0e9dba99
