### ISSUE TITLE
amalgkit metadata for specific SRA-IDs

### ISSUE THREAD

**Issue by Hego-CCTB** [kfuku52/amalgkit#89]
I started working on recreating your vertebrae dataset for the amalgkit paper and it got me thinking. There will be cases of people trying to recreate datasets or trying to work on sequencing data from specific studies. 
So they will already know which SRA-IDs they want to run through amalgkit. It could be really useful to have an alternative mode or just .config file, which takes  a list of SRA-IDs  as input and gets the metadata from just these entries. 

@kfuku52 What do you think?

**Comment by kfuku52** [comment]
It should already be doable by putting the ids in `search_term_keyword.config`.

**Comment by Hego-CCTB** [comment]
Huh, yeah, that seems to work. Never really occured to me, that `search_term_keyword.config`can be used with IDs as well.

Nevermind, then. :D

**Comment by kfuku52** [comment]
It would be nice to clarify it in the Wiki. Please include it in the `metadata`'s instruction page.

**Comment by Hego-CCTB** [comment]
yes!
Wiki needs an overhaul anyway. I'll take care of it!
