### ISSUE TITLE
Amalgkit Wiki overhaul

### ISSUE THREAD

**Issue by Hego-CCTB** [kfuku52/amalgkit#94]
There is a lot of information still missing and some things are not up to date. 
I will work on updating the Wiki.

**Comment by kfuku52** [comment]
I will take care of it if you don't have time.

**Comment by Hego-CCTB** [comment]
I made efforts to update it recently. All of the main functions are up-to-date. What's missing are the optional/support functions: 
- merge
- cstmm
- csca
- sanity
- integrate (kinda). Integrate can be found in the metadata part. Just needs a link to the relevant part.

**Comment by Hego-CCTB** [comment]
This won't take long. I'll continue this! Will be done by the end of the week.

**Comment by kfuku52** [comment]
Great!

**Comment by Hego-CCTB** [comment]
Updated!

**Comment by kfuku52** [comment]
Thanks! I will organize the top page and add some more descriptions whenever possible.
